<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-03-16T18:23:20+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'timezone' => 'America/Denver',
);
