<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-03-16T16:55:38+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'MDS Law Office',
    'version_installed' => '5.7.5.6',
    'misc' => array(
        'access_entity_updated' => 1458147338,
    ),
);
