<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-03-17T10:32:00-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'MDS Law Office change name',
    'version_installed' => '5.7.5.6',
    'misc' => array(
        'access_entity_updated' => 1458166136,
        'latest_version' => '5.7.5.6',
        'favicon_fid' => 0,
        'user_timezones' => false,
        'do_page_reindex_check' => false,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'seo' => array(
        'canonical_url' => '',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'tracking' => array(
            'code' => '<script>
  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');

  ga(\'create\', \'UA-51710677-1\', \'mdslawoffice.com\');
  ga(\'send\', \'pageview\');

</script>
<meta name="google-site-verification" content="laM49myCU5YtxTW3TW8b0oOgZWKtzYpnhqixIWKZ4SI" />',
            'code_position' => 'top',
        ),
    ),
);
